language: generic
sudo: required
dist: xenial

install:
  - sudo apt-get update
  - sudo apt-get install -y debhelper fakeroot devscripts fpc lcl

script:
  - lazbuild -v
  - dpkg-buildpackage -uc -us

notifications:
  email:
    on_success: change
    on_failure: change
