language: generic
sudo: required
dist: xenial

os:
  - linux

install:
  - sudo apt-get update
  - sudo apt-get install -y debhelper fakeroot devscripts fpc lcl

script:
  - lazbuild -v
  - dpkg-buildpackage -uc -us
