language: generic
sudo: required

os:
  - linux

install:
  - sudo apt-get update
  - sudo apt-get install -y debhelper devscripts fpc lcl-utils

script:
  - lazbuild -v
  - dpkg-buildpackage -uc -us
